const KEY="resume-ai-v2";
const empty={name:"",title:"",email:"",phone:"",location:"",linkedin:"",website:"",summary:"",skills:[],experience:[],education:[],projects:[],certifications:[],jobDescription:""};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(empty);let tab="basics";
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));document.querySelector("#saveState").textContent="Saved locally";analyze()};
const toast=m=>{const t=document.querySelector("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
function field(label,key,value,type="input",full=false){return `<div class="field ${full?'full':''}"><label>${label}</label>${type==='textarea'?`<textarea data-key="${key}">${esc(value)}</textarea>`:`<input data-key="${key}" value="${esc(value)}">`}</div>`}
function renderForm(){const f=document.querySelector("#form");if(tab==='basics')f.innerHTML=`<div class="grid">${field('Full name','name',data.name)}${field('Professional title','title',data.title)}${field('Email','email',data.email)}${field('Phone','phone',data.phone)}${field('Location','location',data.location)}${field('LinkedIn','linkedin',data.linkedin)}${field('Website','website',data.website)}${field('Professional summary','summary',data.summary,'textarea',true)}</div>`;
if(tab==='experience')f.innerHTML=`<div id="experienceList">${(data.experience||[]).map((x,i)=>entry('experience',x,i,`<div class="grid">${field('Role','role',x.role)}${field('Company','company',x.company)}${field('Location','location',x.location)}${field('Dates','dates',x.dates)}${field('Bullets (one per line)','bullets',(x.bullets||[]).join('\n'),'textarea',true)}</div>`).join('')}</div><button class="small-btn" onclick="addEntry('experience')">＋ Add experience</button>`;
if(tab==='education')f.innerHTML=`${(data.education||[]).map((x,i)=>entry('education',x,i,`<div class="grid">${field('Degree','degree',x.degree)}${field('School','school',x.school)}${field('Location','location',x.location)}${field('Dates','dates',x.dates)}</div>`).join('')}<button class="small-btn" onclick="addEntry('education')">＋ Add education</button>`;
if(tab==='skills')f.innerHTML=`<div class="field"><label>Skills</label><textarea id="skillsInput" placeholder="Type skills separated by commas">${esc((data.skills||[]).join(', '))}</textarea></div><div class="field"><label>Certifications</label><textarea id="certInput" placeholder="One certification per line">${esc((data.certifications||[]).join('\n'))}</textarea></div>`;
if(tab==='projects')f.innerHTML=`${(data.projects||[]).map((x,i)=>entry('projects',x,i,`<div class="grid">${field('Project name','name',x.name)}${field('Technologies','tech',(x.tech||[]).join(', '))}${field('Description','description',x.description,'textarea',true)}</div>`).join('')}<button class="small-btn" onclick="addEntry('projects')">＋ Add project</button>`;
if(tab==='target')f.innerHTML=`<div class="field"><label>Paste job description</label><textarea id="jd" style="min-height:300px" placeholder="Paste the job description here to calculate keyword match and tailor your resume.">${esc(data.jobDescription)}</textarea></div><button class="primary" id="analyzeBtn">Analyze job match</button><div id="analysis" class="section-card" style="margin-top:15px"></div>`;bindInputs();if(tab==='target')document.querySelector('#analysis').innerHTML=analysisHTML(lastAnalysis||{score:0,matched:[],missing:[]});}
function entry(type,x,i,inside){return `<div class="section-card"><div class="section-head"><b>${x.role||x.degree||x.name||`New ${type}`}</b><button class="small-btn danger" onclick="removeEntry('${type}',${i})">Remove</button></div>${inside}</div>`}
function bindInputs(){document.querySelectorAll('[data-key]').forEach(el=>el.oninput=()=>{data[el.dataset.key]=el.value;save()});const s=document.querySelector('#skillsInput');if(s)s.oninput=()=>{data.skills=s.value.split(',').map(x=>x.trim()).filter(Boolean);save()};const c=document.querySelector('#certInput');if(c)c.oninput=()=>{data.certifications=c.value.split('\n').map(x=>x.trim()).filter(Boolean);save()};const jd=document.querySelector('#jd');if(jd)jd.oninput=()=>{data.jobDescription=jd.value;save()};const ab=document.querySelector('#analyzeBtn');if(ab)ab.onclick=analyze}
function addEntry(type){data[type].push(type==='experience'?{role:'',company:'',location:'',dates:'',bullets:['']} : type==='education'?{degree:'',school:'',location:'',dates:''}:{name:'',tech:[],description:''});renderForm();save()}
function removeEntry(type,i){data[type].splice(i,1);renderForm();save()}
document.addEventListener('input',e=>{if(e.target.matches('[data-key]')){const card=e.target.closest('.section-card');if(!card)return;const cards=[...document.querySelectorAll('#form .section-card')];const type=tab;let idx=cards.indexOf(card);if(type==='experience'||type==='education'||type==='projects'){const key=e.target.dataset.key;const map={experience:data.experience,education:data.education,projects:data.projects};if(map[type][idx])map[type][idx][key]=key==='bullets'?e.target.value.split('\n').filter(Boolean):key==='tech'?e.target.value.split(',').map(x=>x.trim()).filter(Boolean):e.target.value;save()}}});
let lastAnalysis=null;
function analysisHTML(a){return `<div><b>Job match: ${a.score||0}/100</b><p>Matched keywords: ${(a.matched||[]).slice(0,18).join(', ')||'None yet'}</p><p>Missing keywords: ${(a.missing||[]).slice(0,18).join(', ')||'Great coverage'}</p></div>`}
async function analyze(){try{const r=await fetch('/api/ats/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resume:data,jobDescription:data.jobDescription})});lastAnalysis=await r.json();document.querySelector('#score').textContent=lastAnalysis.score||0;if(tab==='target'&&document.querySelector('#analysis'))document.querySelector('#analysis').innerHTML=analysisHTML(lastAnalysis)}catch{}}
function preview(){const p=document.querySelector('#preview');p.innerHTML=`<div class="resume-name">${esc(data.name||'Your Name')}</div><div class="resume-title">${esc(data.title||'Professional Title')}</div><div class="contact">${[data.email,data.phone,data.location,data.linkedin,data.website].filter(Boolean).map(esc).join(' · ')||'email@example.com · Location'}</div>${data.summary?`<section class="rsec"><h4>PROFILE</h4><p>${esc(data.summary)}</p></section>`:''}${data.experience?.length?`<section class="rsec"><h4>EXPERIENCE</h4>${data.experience.map(x=>`<div class="job"><div class="jobtop"><b>${esc(x.role)}</b><span>${esc(x.dates)}</span></div><em>${esc(x.company)}${x.location?' · '+esc(x.location):''}</em><ul>${(x.bullets||[]).filter(Boolean).map(b=>`<li>${esc(b)}</li>`).join('')}</ul></div>`).join('')}</section>`:''}${data.education?.length?`<section class="rsec"><h4>EDUCATION</h4>${data.education.map(x=>`<div class="job"><div class="jobtop"><b>${esc(x.degree)}</b><span>${esc(x.dates)}</span></div><em>${esc(x.school)}${x.location?' · '+esc(x.location):''}</em></div>`).join('')}</section>`:''}${data.skills?.length?`<section class="rsec"><h4>SKILLS</h4><div class="chips">${data.skills.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></section>`:''}${data.projects?.length?`<section class="rsec"><h4>PROJECTS</h4>${data.projects.map(x=>`<div class="job"><b>${esc(x.name)}</b><p>${esc(x.description)}</p><span>${esc((x.tech||[]).join(' · '))}</span></div>`).join('')}</section>`:''}${data.certifications?.length?`<section class="rsec"><h4>CERTIFICATIONS</h4><p>${data.certifications.map(esc).join(' · ')}</p></section>`:''}`}
function render(){renderForm();preview();analyze()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.tab;renderForm()});
document.querySelector('#template').onchange=e=>document.querySelector('#preview').dataset.template=e.target.value;
document.querySelector('#sampleBtn').onclick=()=>{data={...empty,name:'Narsing Beesetti',title:'MuleSoft Developer | Production Support',email:'narsing@example.com',phone:'+91 90000 00000',location:'Hyderabad, India',linkedin:'linkedin.com/in/narsing',summary:'MuleSoft developer with experience in API-led connectivity, DataWeave, REST integrations and production support. Skilled in monitoring, incident resolution and building reliable integrations.',skills:['MuleSoft','Anypoint Platform','DataWeave 2.0','REST API','APIKit','Java','Git','Dynatrace'],experience:[{role:'MuleSoft Developer',company:'Technology Company',location:'India',dates:'2023 — Present',bullets:['Developed REST APIs using MuleSoft and API-led connectivity patterns.','Resolved production incidents and improved integration stability through monitoring and root-cause analysis.','Created DataWeave transformations and reusable integration components.']}],education:[{degree:'Bachelor of Technology',school:'University',location:'India',dates:'2019 — 2023'}],projects:[{name:'Bank Account API',tech:['MuleSoft','DataWeave','MySQL'],description:'Built API-led banking services for account creation, retrieval and updates.'}],certifications:[],jobDescription:''};save();render()};
document.querySelector('#exportBtn').onclick=()=>window.print();
async function aiAction(url,body,title){document.querySelector('#modal').classList.remove('hidden');document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalBody').innerHTML='<p class="suggestion">Generating suggestions…</p>';try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);document.querySelector('#modalBody').innerHTML=`<div class="suggestion">${esc(d.result||d.rewrittenResume||'No result')}</div>`}catch(e){document.querySelector('#modalBody').innerHTML=`<p class="suggestion">${esc(e.message)}</p>`}}
document.querySelector('#summaryBtn').onclick=()=>aiAction('/api/ai/summary',{resume:data,targetRole:data.title},'AI summary options');
document.querySelector('#tailorBtn').onclick=()=>{if(!data.jobDescription){toast('Add a job description first');tab='target';document.querySelector('[data-tab="target"]').click();return}aiAction('/api/ai/tailor',{resume:data,jobDescription:data.jobDescription},'Tailored resume recommendations')};
document.querySelector('#closeModal').onclick=()=>document.querySelector('#modal').classList.add('hidden');
render();
